// Archivo generado por build_standalone.py: NO editar a mano.
// Copia de datos/catalogo_modulos.json y datos/base_sitios.json para
// cuando la aplicación se abre sin servidor.
window.DATOS_RESPALDO = {
  "catalogo": {
    "descripcion": "Catálogo de módulos fotovoltaicos. Archivo editable: para agregar una referencia basta copiar un bloque, cambiar sus valores y guardar. Valores eléctricos en STC (1000 W/m², 25 °C, AM1.5). Coeficientes de temperatura en %/°C.",
    "fechaActualizacion": "2026-10-04",
    "modulos": [
      {
        "id": "longi-lr5-54htb-450m",
        "fabricante": "LONGi",
        "modelo": "LR5-54HTB-450M",
        "potenciaW": 450,
        "vocV": 40.23,
        "iscA": 14.31,
        "vmpV": 33.96,
        "impA": 13.27,
        "coefVocPctC": -0.23,
        "coefPmaxPctC": -0.29,
        "coefIscPctC": 0.05,
        "celdasSerie": 54,
        "areaM2": 1.953,
        "eficienciaPct": 23.0,
        "temperaturaNominalC": 45,
        "tipoTemperaturaNominal": "NOCT",
        "fuente": "https://static.longi.com/Hi_MO_X6_LR_5_54_HTB_440_450_M_V1_30_30_and_15_V19_ES_81c0bd4e24.pdf",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "trina-tsm-deg19c20-550",
        "fabricante": "Trina Solar",
        "modelo": "TSM-DEG19C.20 (550 W)",
        "potenciaW": 550,
        "vocV": 38.1,
        "iscA": 18.39,
        "vmpV": 31.8,
        "impA": 17.29,
        "coefVocPctC": -0.25,
        "coefPmaxPctC": -0.34,
        "coefIscPctC": 0.04,
        "celdasSerie": 55,
        "areaM2": 2.613,
        "eficienciaPct": 21.0,
        "temperaturaNominalC": 43,
        "tipoTemperaturaNominal": "NOCT",
        "fuente": "https://static.trinasolar.com/sites/default/files/Datasheet_Vertex_TSM-DEG19C.20_535-555W_2022_C1.pdf",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "canadian-cs62-66tb-625hp",
        "fabricante": "Canadian Solar",
        "modelo": "CS6.2-66TB-625HP",
        "potenciaW": 625,
        "vocV": 48.6,
        "iscA": 16.14,
        "vmpV": 41.4,
        "impA": 15.11,
        "coefVocPctC": -0.25,
        "coefPmaxPctC": -0.29,
        "coefIscPctC": 0.045,
        "celdasSerie": 66,
        "areaM2": 2.701,
        "eficienciaPct": 23.1,
        "temperaturaNominalC": 41,
        "tipoTemperaturaNominal": "NMOT",
        "fuente": "https://www.canadiansolar.com/wp-content/uploads/sites/3/2026/03/CS-Datasheet-TOPBiHiKu6_Anti-Hail_CS6.2-66TB-HP_v1.2_F83_D6_TX.pdf",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "longi-lr8-66hvd-650m",
        "fabricante": "LONGi",
        "modelo": "LR8-66HVD-650M",
        "potenciaW": 650,
        "vocV": 49.72,
        "iscA": 16.54,
        "vmpV": 40.98,
        "impA": 15.86,
        "coefVocPctC": -0.2,
        "coefPmaxPctC": -0.26,
        "coefIscPctC": 0.05,
        "celdasSerie": 66,
        "areaM2": 2.701,
        "eficienciaPct": 24.06,
        "temperaturaNominalC": 45,
        "tipoTemperaturaNominal": "NMOT",
        "fuente": "https://eu.longi.com/longi-solar-panels-datasheets/lr8-66hvd-640-670m",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "referencia-tdr-550",
        "referenciaTdR": true,
        "fabricante": "Módulo de referencia del TdR",
        "modelo": "550 Wp (caso de prueba)",
        "potenciaW": 550,
        "vocV": 49.5,
        "iscA": 14.0,
        "vmpV": 41.5,
        "impA": 13.3,
        "coefVocPctC": -0.27,
        "coefPmaxPctC": -0.35,
        "coefIscPctC": 0.05,
        "celdasSerie": 72,
        "areaM2": 2.58,
        "eficienciaPct": 21.3,
        "temperaturaNominalC": 45,
        "tipoTemperaturaNominal": "NOCT",
        "fuente": "TdR Reto 02, sección 7.2. Valores declarados para el caso de prueba; no corresponde a un producto comercial.",
        "fechaConsulta": "2026-10-04"
      }
    ]
  },
  "sitios": {
    "descripcion": "Base de datos local de recurso solar. Irradiación sobre el plano del generador en kWh/m²·día. Los valores mensuales son H(i)_m de PVGIS divididos por los días de cada mes; el anual es H(i)_y dividido por 365.",
    "fechaActualizacion": "2026-10-04",
    "sitios": [
      {
        "id": "nazareth-caso-prueba",
        "casoPrueba": true,
        "nombre": "Nazareth, Alta Guajira — caso de prueba (TdR)",
        "latitud": 12.18,
        "longitud": -71.28,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 5.8,
        "irradiacionMesCritico": 5.2,
        "mensual": null,
        "fuente": "TdR Reto 02, sección 7.1: valores declarados en el plano del generador para el caso de prueba estandarizado. El TdR no entrega los doce valores mensuales.",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "nazareth-pvgis",
        "nombre": "Nazareth, Alta Guajira (PVGIS)",
        "latitud": 12.175,
        "longitud": -71.282,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 6.37,
        "irradiacionAnualKWhm2Anio": 2323.46,
        "mensual": [
          6.42,
          6.89,
          6.88,
          6.61,
          6.15,
          6.2,
          6.44,
          6.59,
          6.5,
          5.96,
          5.73,
          6.06
        ],
        "fuente": "PVGIS-5, base de datos PVGIS-ERA5 (re.jrc.ec.europa.eu/pvg_tools), sistema conectado a red",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "unimagdalena-santa-marta",
        "nombre": "Universidad del Magdalena, Santa Marta",
        "latitud": 11.226,
        "longitud": -74.188,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 5.01,
        "irradiacionAnualKWhm2Anio": 1828.48,
        "mensual": [
          5.74,
          6.18,
          5.77,
          5.11,
          4.61,
          4.44,
          4.44,
          4.54,
          4.8,
          4.64,
          4.68,
          5.25
        ],
        "fuente": "PVGIS-5, base de datos PVGIS-ERA5 (re.jrc.ec.europa.eu/pvg_tools), sistema conectado a red",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "ied-san-jose-pueblo-viejo",
        "nombre": "IED San José, Pueblo Viejo (Magdalena)",
        "latitud": 10.997,
        "longitud": -74.279,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 5.24,
        "irradiacionAnualKWhm2Anio": 1912.28,
        "mensual": [
          5.96,
          6.4,
          6.05,
          5.38,
          4.84,
          4.68,
          4.7,
          4.77,
          5.03,
          4.85,
          4.82,
          5.48
        ],
        "fuente": "PVGIS-5, base de datos PVGIS-ERA5 (re.jrc.ec.europa.eu/pvg_tools), sistema conectado a red",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "aeropuerto-valledupar",
        "nombre": "Aeropuerto Alfonso López, Valledupar",
        "latitud": 10.429,
        "longitud": -73.249,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 5.12,
        "irradiacionAnualKWhm2Anio": 1870.13,
        "mensual": [
          6.02,
          6.33,
          5.81,
          4.98,
          4.44,
          4.55,
          4.78,
          4.79,
          4.88,
          4.65,
          4.72,
          5.62
        ],
        "fuente": "PVGIS-5, base de datos PVGIS-ERA5 (re.jrc.ec.europa.eu/pvg_tools), sistema conectado a red",
        "fechaConsulta": "2026-10-04"
      },
      {
        "id": "uis-bucaramanga",
        "nombre": "UIS, Bucaramanga (Santander)",
        "latitud": 7.141,
        "longitud": -73.12,
        "inclinacionGrados": 12,
        "azimutGrados": 0,
        "irradiacionAnual": 4.66,
        "irradiacionAnualKWhm2Anio": 1700.99,
        "mensual": [
          5.39,
          5.5,
          5.05,
          4.48,
          3.98,
          3.9,
          4.09,
          4.48,
          4.83,
          4.62,
          4.57,
          5.08
        ],
        "fuente": "PVGIS-5, base de datos PVGIS-ERA5 (re.jrc.ec.europa.eu/pvg_tools), sistema conectado a red",
        "fechaConsulta": "2026-10-04"
      }
    ]
  }
};
